INSERT INTO EXCHANGE_API (NAME) VALUES('hitBtc')
INSERT INTO EXCHANGE_API (NAME) VALUES('Binance')

INSERT INTO EXCHANGE_CURRENCY (NAME) VALUES('EOSBTC')
INSERT INTO EXCHANGE_CURRENCY (NAME) VALUES('ETHBTC')
INSERT INTO EXCHANGE_CURRENCY (NAME) VALUES('BNBBTC')